### `.streamlit/secrets.toml`
### Secret Management
### Open-Source, hosted on https://github.com/DrBenjamin/dissertation-movement-analysis
### Please reach out to s2616861@ed.ac.uk for any questions
### MinIO Setup
# URL: https://minio.seriousbenentertainment.org:9001/login
MINIO_ENDPOINT = "https://minio.seriousbenentertainment.org:9000"  # "https://minio.seriousbenentertainment.org:9000" or "http://212.227.102.172:9000"
MINIO_ACCESS_KEY = "health"
MINIO_SECRET_KEY = "NOentry#23"
MINIO_SECURE = true  # Use HTTPS for secure connection
